#!/bin/bash

for samp1 in `ls /processing/PROCESSING/MIGRATED/Bioinformatics/ewilkie/01-Projects/Embryo_staging/01-Shanghai_transfer/spatial/E7.5/Embryo2_Ref/*.fastq.bz2`;
do
	echo ${samp1}
	samp_name=`echo ${samp1} | awk '{gsub("/processing/PROCESSING/MIGRATED/Bioinformatics/ewilkie/01-Projects/Embryo_staging/01-Shanghai_transfer/spatial/E7.5/Emryo2_Ref/","",$0); print}'`
	echo ${samp_name}
	/processing/PROCESSING/Embryology/tools/salmon quant \
		-p 8 \
		-i /processing/PROCESSING/Embryology/tools/genomes/gencode_M17_index \
		-l A \
		-r ${samp1} \
		-o ./quants/;
		mv ./quants/quant.sf /processing/PROCESSING/Embryology/posteil/Salmon/quants_SE/${samp_name}_quant.sf
done
